### ISSUE TITLE
Raspberry pi egl fails

### ISSUE THREAD

**Issue by clienthax** [thp/apkenv#21]
Is it possible to get a platform file for the raspberry pi, i have managed to get libsdl-gles to compile and install, if it works is another matter..

Since there wasn't a platform file and the n9xx code wouldn't compile (references to sdl1.3 ?) i tryed pandora=1 
Currently getting a egl surface on screen but the program kicks out the following
http://i.imgur.com/C1qEb1D.png

**Comment by kika123** [comment]
This bug should be closed.
