### ISSUE TITLE
Thumb hooks not compatible with armv6

### ISSUE THREAD

**Issue by clienthax** [thp/apkenv#47]
-e      CC (TH) debug/wrappers/wrapper_code_thumb.o
/tmp/ccQR3dE2.s: Assembler messages:
/tmp/ccQR3dE2.s:25: Error: invalid register list to push/pop instruction -- `push {r0-r11,lr}'
/tmp/ccQR3dE2.s:26: Error: selected processor does not support Thumb mode `ldrd r0,fun'
/tmp/ccQR3dE2.s:28: Error: selected processor does not support Thumb mode `ldrd r1,name'
/tmp/ccQR3dE2.s:29: Error: selected processor does not support Thumb mode `ldrd r2,str'
/tmp/ccQR3dE2.s:30: Error: selected processor does not support Thumb mode `ldrd r4,tc'
/tmp/ccQR3dE2.s:32: Error: invalid register list to push/pop instruction -- `pop {r0-r11,lr}'
/tmp/ccQR3dE2.s:40: Error: lo register required -- `ldr pc,fun'
make: *** [debug/wrappers/wrapper_code_thumb.o] Error 1

**Comment by thp** [comment]
Closing, since the currently tested platforms (Maemo 5, Harmattan, Pandora, ...) are armv7 at least I think.
