### ISSUE TITLE
Cannot compile on x86_64

### ISSUE THREAD

**Issue by amentis** [thp/apkenv#74]
linker/dlfcn.c:267:17: error: initializer element is not constant
linker/dlfcn.c:267:17: note: (near initialization for ‘apkenv_libdl_symtab[6].st_value’)

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --disable-multilib --disable-werror --enable-checking=release
Thread model: posix
gcc version 6.3.1 20170109 (GCC)

**Comment by thp** [comment]
Probably won't work with x86_64, only tested with ARM.

Note that we unconditionally define this here:
https://github.com/thp/apkenv/blob/master/linker/linker.h#L32

You'd have to do a bit of porting to get it working on x86 or even x86_64.
