### ISSUE TITLE
Build fails on maemo-leste / droid 4

### ISSUE THREAD

**Issue by clort81** [thp/apkenv#77]
user@ml1:/big/src/apkenv$ make
makefile:33: Using SDL 1.2 libraries
        CC      compat/gles2_wrappers.o
<command-line>: error: two or more data types in declaration specifiers
make: *** [makefile:89: compat/gles2_wrappers.o] Error 1

Unfortunately make isn't giving me the line of gles2_wrappers.c that it doesn't like.
The structs end with semicolons, so that's correct.  Idk what else could be the problem.

**Comment by thp** [comment]
Try building with:

    make V=1

Also, are your GL ES headers installed and sane?

If maemo-leste is more Maemo 5 than MeeGo 1.2 Harmattan, pass `PLATFORM=fremantle` (default is `harmattan`) to the make command as well. Make sure to clean before rebuilding with different `PLATFORM` values.

**Comment by thp** [comment]
@clort81 Did `make V=1` result in any useful clues?

**Comment by thp** [comment]
Closing. Please reopen if building is still an issue.
